//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KY.Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NorthwindEntities : DbContext
    {
        public NorthwindEntities()
            : base("name=NorthwindEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Order_Details> Order_Details { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Products> Products { get; set; }
    
        public virtual ObjectResult<Usp_DetallePedidoListar_Result> Usp_DetallePedidoListar(Nullable<int> nro_Orden)
        {
            var nro_OrdenParameter = nro_Orden.HasValue ?
                new ObjectParameter("Nro_Orden", nro_Orden) :
                new ObjectParameter("Nro_Orden", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_DetallePedidoListar_Result>("Usp_DetallePedidoListar", nro_OrdenParameter);
        }
    
        public virtual ObjectResult<Usp_OrdersClienteListar_Result> Usp_OrdersClienteListar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_OrdersClienteListar_Result>("Usp_OrdersClienteListar");
        }
    }
}
